### PR TITLE
Added support for IO::String and "in memory" files, other minor fixes

### PR DESCRIPTION
**Pull request by mpryvkin**

### CODE REVIEW

**Comment by mpryvkin** [comment]
Any progress on this?

**Comment by cnighswonger** [comment]
Hey Michael,

I hope to roll a release before the end of the year to include this and
several other bug-fixes/enhancements.

Thanks for your work!

Kind regards,
Chris

**Comment by mpryvkin** [comment]
Thanks, that is really appreciated. Hopefully this pull request https://github.com/cnighswonger/PDF-Reuse/pull/6 can make into the release as well, it solves another issue I recently discovered.

**Comment by cnighswonger** [comment]
Thanks Michael!

**Pull request closed without merging**
